test loading from welcome page
mrc-ide/shiny90 pull request #20
Opened 2018-10-01 13:15 UTC by littledice

2018-10-01 13:33 UTC, MartinEden requested changes

2018-10-01 13:33 UTC, MartinEden commented on src/tests/logic.R
> +    fileUpload$sendKeysToElement(list(key = "enter"))
Maybe we could factor out the common logic between this and `uploadSpectrumFile` into a helper function?

2018-10-01 13:33 UTC, MartinEden commented on src/tests/testthat/testLoading.R
> +    expectTextEqual("Upload spectrum file(s)", panelTitle)
It would be good to check that at least some aspect of this save file - e.g. the notes, or the country - has been restored.

2018-10-03 11:21 UTC, MartinEden requested changes
One tiny change more - feel free to merge once you've made it.

2018-10-03 11:21 UTC, MartinEden commented on src/tests/logic.R
> +uploadFile <- function(wd, dir="../../../sample_files/", filename = "Malawi_2018_version_8.PJNZ", inputId) {
Seems a bit weird to have default values for these parameters. I think it's fine just to have defaults on the two more specific functions.

2018-10-03 11:31 UTC, littledice commented on src/tests/logic.R
> +uploadFile <- function(wd, dir="../../../sample_files/", filename = "Malawi_2018_version_8.PJNZ", inputId) {
Leaving the default for dir, removing the one for filename :+1:

2018-10-03 11:32 UTC, merged