validation and selenium tests for program data uploading
mrc-ide/shiny90 pull request #26
Opened 2018-10-04 14:54 UTC by littledice

2018-10-04 16:10 UTC, littledice commented on src/server/survey_and_program_data.R
> +    long$country <- as.character(long$country)
Have reintroduced `country` to the table, so that we can do basic validation of any uploaded data.

2018-10-05 09:38 UTC, MartinEden requested changes
Logic looks good and code is clear. Just two minor quibbles

2018-10-05 09:38 UTC, MartinEden commented on src/tests/testthat/testProgramData.R
> +uploadFilesAndSwitchTab <- function() {
Maybe `uploadSpectrumFileAndSwitchTab`?

2018-10-05 09:38 UTC, MartinEden commented on src/ui/input_panels.R
> +            rhandsontable::rHandsontableOutput("hot_program")
What's going on with the indentation here?

2018-10-08 09:24 UTC, MartinEden approved these changes

2018-10-11 10:29 UTC, merged