i116: Save outputs to digest
mrc-ide/shiny90 pull request #30
Opened 2018-10-11 12:43 UTC by MartinEden

https://vimc.myjetbrains.com/youtrack/issue/mrc-116

2018-10-11 14:36 UTC, MartinEden commented
This is a pretty big one I'm afraid. In particular, `model_outputs.R` and `model_run.R` have been smashed together and then taken apart in a different way, so that we can store just the bits we want as intermediate results.

It's worth noting that saving out `optim` is only about 500 bytes - it's tiny. But saving out the result of simul.test is a few MB. It would be nice if we could save out less there; given that @jeffeaton  suggested that the simul code might have some room for optimization, it would be worth bringing up whether the data size could be reduced too.

2018-10-11 15:36 UTC, hillalex requested changes
The code re-organisation actually feels cleaner/clearer than before, just 1 issue with functionality. (And thank goodness the tests seem to have stabilised finally!)

2018-10-11 15:36 UTC, littledice commented on src/server/save_and_load.R
> +    if (!is.null(modelRunState$optim)) {
At the moment, if outputs become stale we just set `modelRunState$state` to "stale", so as currently stands the stale outputs will still be included in the saved digest. To fix we could either a) change this condition to also check that `state != "stale"` or b) set `optim` to null when the output becomes stale. I don't have a strong preference as to which!

2018-10-12 12:31 UTC, hillalex approved these changes

2018-10-12 12:31 UTC, merged